### ISSUE TITLE
建议增加OpenAI的地址配置

### ISSUE THREAD

**Issue by zhaoquanhua** [ZJYCP/HbuilderX-ArtiCode#1]
建议增加OpenAI的地址配置，因国内原因，采取一些非常规方法
如：https://github.com/yetone/bob-plugin-openai-translator/issues/26

**Comment by ZJYCP** [comment]
您的来信我已收到，谢谢。

**Comment by ZJYCP** [comment]
这个配置项在刚刚已经加进去了，感谢关注 ＾ω＾
